#!/bin/bash

if [ ! "$(git config --local user.name)" ] && [ "$(git config user.name)" = whoami ]; then
    cat <<EOM >&2
*** Who are you?

Hint:
    git config --local user.name <NAME>
    git config --local user.email <EMAIL>
EOM
    exit 1
fi
